version: "3.9"

services:
  student-service:
    build: ./student-service
    container_name: student-service
    env_file:
      - ./student-service/.env
    ports:
      - "8001:8001"

  enrollment-service:
    build: ./enrollment-service
    container_name: enrollment-service
    env_file:
      - ./enrollment-service/.env
    ports:
      - "8000:8000"
