services:
  api-gateway:
    build: ./backend/api-gateway-service
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8001
      - COURSE_SERVICE_URL=http://course-service:8002
      - ENROLLMENT_SERVICE_URL=http://enrollment-service:8003
      - GRADES_SERVICE_URL=http://grades-service:8004
      - REPORTING_SERVICE_URL=http://reporting-service:8005
      - SCHEDULE_SERVICE_URL=http://schedule-service:8006
      - NOTIFICATION_SERVICE_URL=http://notification-service:8007
    depends_on:
      - user-service
      - course-service
      - enrollment-service
      - grades-service
      - reporting-service
      - schedule-service
      - notification-service
    volumes:
      - ./backend/api-gateway-service:/app
      - ./frontend/app/login:/app/frontend_login
      - ./frontend/app/admin:/app/frontend_admin
      - ./frontend/app/student:/app/frontend_student
      - ./frontend/app/faculty:/app/frontend_faculty
      - ./frontend/public:/app/public
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8001:8001"

  course-service:
    build: ./backend/course-service
    container_name: course-service
    ports:
      - "8002:8002"

  enrollment-service:
    build: ./backend/enrollment-service
    container_name: enrollment-service
    ports:
      - "8003:8003"

  grades-service:
    build: ./backend/grades-service
    container_name: grades-service
    ports:
      - "8004:8004"

  reporting-service:
    build: ./backend/reporting-service
    container_name: reporting-service
    ports:
      - "8005:8005"
    environment:
      - EXPORT_DIR=/app/exports

  schedule-service:
    build: ./backend/schedule-service
    container_name: schedule-service
    ports:
      - "8006:8006"

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    ports:
      - "8007:8007"
