FROM python:3.11-slim

WORKDIR /app

COPY src/ ./src

RUN pip install uvicorn fastapi
# RUN pip install --upgrade pip
RUN pip install pytest httpx pytest-asyncio
RUN pip install "pydantic<2.0"
RUN pip install pydantic-settings


# RUN pip install -r requirements.txt
# Set PYTHONPATH to include src
ENV PYTHONPATH=/app/src

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]