FROM python:3.11-slim

WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/ ./src

# Set PYTHONPATH to include src
ENV PYTHONPATH=/app/src

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
CMD ["uvicorn", "main:app"]