FROM python:3.11-slim

WORKDIR /app

COPY src/ ./src

RUN pip install uvicorn fastapi
# RUN pip install --upgrade pip
RUN pip install pytest httpx pytest-asyncio
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include src
ENV PYTHONPATH=/app/src

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
CMD ["uvicorn", "main:app"]